### PR TITLE
Avoid Rails 5.2 deprecation warning

### PR DESCRIPTION
**Pull request by shanecav84**
> DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "LOWER(school_districts.name) ASC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from preprocess_order_args at /Users/shanecav/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:1129)

### CODE REVIEW

**Comment by shanecav84** [comment]
*bump*

**Comment by shanecav84** [comment]
@bigtunacan Could you take a look at this?

**Comment by shanecav84** [comment]
@bigtunacan

**Comment by shanecav84** [comment]
@risuiowa Could you take a look at this?

**Review by sundus-y — COMMENTED** [review]
LGTM

**Comment by shanecav84** [comment]
🎉 Thanks!

**Comment by shanecav84** [comment]
@sundus-y When do you intend to do a new release?

**Comment by sundus-y** [comment]
@shanecav84 In the next couple of hours if not minutes. ⏲

**Comment by sundus-y** [comment]
@shanecav84 All done. 📦

**Comment by shanecav84** [comment]
Thanks!

**Pull request merged**
